name: setup-pesde
description: GitHub action to install and run pesde; a Luau package manager.
author: ewd3v

inputs:
  version:
    description: "`pesde` git tag (usually in the form vx.x.x)"
    required: false
  path:
    description: "Path to the `pesde.toml` directory"
    default: "."
    required: false
  cache:
    description: "Whether to enable caching"
    default: "false"
    required: false
  token:
    description: "GitHub token via `github.token`"
    default: "${{ github.token }}"
    required: false

runs:
  using: "composite"
  steps:
    - name: Download pesde
      run: |
        case ${{ runner.arch }} in
          "X86" | "X64") fileArch="x86_64" ;;
          "ARM" | "ARM64") fileArch="aarch64" ;;
        esac

        case ${{ runner.os }} in
          Linux) pattern="*linux-$fileArch.zip" ;;
          macOS) pattern="*macos-$fileArch.zip" ;;
          Windows) pattern="*windows-$fileArch.zip" ;;
        esac

        gh release download ${{ inputs.version }} --repo pesde-pkg/pesde --pattern $pattern
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash

    - name: Install pesde
      run: |
        unzip pesde*.zip
        ./pesde self-install
      shell: bash

    - name: Delete artifacts
      run: |
        rm pesde*.zip
        if ${{ runner.os == 'Windows' }}; then
          rm pesde.exe
        else
          rm pesde
        fi
      shell: bash

    - name: Set environment variable
      if: runner.os == 'Windows'
      run: echo "$HOME/.pesde/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    - name: Set environment variable
      if: runner.os != 'Windows'
      run: echo "$HOME/.pesde/bin" >> $GITHUB_PATH
      shell: bash

    - name: Authenticate
      run: pesde auth login --token ${{ inputs.token }}
      shell: bash

    - name: Cache binaries
      if: ${{ inputs.cache == true || inputs.cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.pesde
        key: ${{ runner.os }}-pesde-${{ hashFiles(format('{0}/{1}', inputs.path, 'pesde.lock')) }}
        restore-keys: ${{ runner.os }}-pesde-

    - name: Install dependencies
      run: |
        cd ${{ inputs.path }}
        pesde install
      shell: bash

branding:
  icon: package
  color: yellow
